### ISSUE TITLE
Permission to use your code on my free website

### ISSUE THREAD

**Issue by DanielQuiz** [KingOfTNT10/KingOfTNT10.github.io#2]
Hello,

I'm the owner of a free IQ quiz website and I would like to know if I can use your code and modify it for my website.
The modification will be to automatically generate a puzzle on a daily basis.
I would like to provide free puzzles to people..
It is not clear if your code is protected or not by a license.

Thank You!
Daniel

**Comment by KingOfTNT10** [comment]
> Hello,
> 
> I'm the owner of a free IQ quiz website and I would like to know if I can use your code and modify it for my website.
> The modification will be to automatically generate a puzzle on a daily basis.
> I would like to provide free puzzles to people..
> It is not clear if your code is protected or not by a license.
> 
> Thank You!
> Daniel

Hi daniel!
For sure, thanks for asking me. You can use the code for your website.
I would appreciate credit if possible (by the name K9Dev) but its your choice.

**Comment by idanhadari** [comment]
Sure I'll be happy to add you a credit.. This is the website: freetestiq.com
Thank a lot. You did a great job :-)

**Comment by KingOfTNT10** [comment]
Thanks!

**Comment by KingOfTNT10** [comment]
@DanielQuiz If you add credit just keep this in:
![image](https://user-images.githubusercontent.com/66069146/233839480-04ce2797-6f8d-4014-84e9-f3388a7134da.png)

**Comment by KingOfTNT10** [comment]
Hi @DanielQuiz I've noticed the matchstick website is up, But still could not find the credit. Could you please point me to the credit's location or add one as you promised.
Thanks!

**Comment by KingOfTNT10** [comment]
Hi @idanhadari I've noticed the matchstick website is up, But still could not find the credit. Could you please point me to the credit's location or add one as you promised.
Thanks!

**Comment by idanhadari** [comment]
Hi @KingOfTNT10, I'm still working on the page, but I have just added the credit as requested.
Here is a link to the page:
https://www.freetestiq.com/matchsticks/index.html?eq=NCsxMD04

Thanks,
Daniel
